name: Build

on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install llvm
        run: sudo apt install llvm-10-dev
      - name: generate build script
        run: cmake .
      - name: build project
        run: make all
      - name: run unit testing
        run: make test
